### PR TITLE
Use Objects.equals

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by simonpoole** [comment]
We need to restrict the use of Java 8 features and APIs to the Android supported subset see https://developer.android.com/studio/write/java8-support, and I'm fairly sure (as in Android documentation has been known to be very wrong) that Objects is not supported before API 19 even when building against a current release.
 
Vespucci currently supports back to Android 9, and supporting back to 16 is not uncommon.

**Comment by simonpoole** [comment]
Objects is actually a Java 7 API, my bad, but it doesn't change the basic issue. As the Android support libs provide a ObjectsCompat class, I believe we can not rely as I suspected above that Objects is available before API 19.

**Comment by simon04** [comment]
Then, let's implement it ourselves – done in d7aa083.

**Comment by simonpoole** [comment]
Rebased and merged in https://github.com/simonpoole/OpeningHoursParser/commit/27f5ff68b242d6729921ac3fe720841db73fc8ea

Note the pointer wrt Android was more general so that we don't have to end up redoing less trivial things, unluckily this is rather tricky to protect against automatically. 

My current favourite is mistakenly using Integer.min/max (which is a Java 8ism) vs Math.min/max naturally every thing will compile perfectly and work in the integration tests, and then fail miserably on oldish devices (on which we cant run the tests).

**Pull request closed without merging**
