### PR TITLE
make Rule constructor public

### PR DESCRIPTION
**Pull request by matkoniecz**
Currently to build an empty Rule object I need to use following as a workaround:

```
        ByteArrayInputStream input = new ByteArrayInputStream("".getBytes(StandardCharsets.UTF_8));
        OpeningHoursParser parser = new OpeningHoursParser(input);
        Rule emptyRule;
        try {
            ArrayList<Rule> rules = parser.rules(true);
            emptyRule = rules.get(0);
        } catch (ParseException e) {
            e.printStackTrace();
            throw new RuntimeException();
        }
```

To avoid XY problem: I want an empty Rule object as I want to check whatever given opening_hours object is using certain subset of opening hours syntax. To do this I

- create an empty `Rule` object
- add to this empty rule only constructs known to be supported, copying them from the original rule
- compare whatever it equals original one

Alternative solution would be to check for all constructs known to be unsupported on the Rule object, but I think that it is far more likely to fail due to missing something.

### CODE REVIEW

**Comment by matkoniecz** [comment]
And to make this less theoretical - code that I mentioned is at https://github.com/westnordost/StreetComplete/compare/master...matkoniecz:resurvey (in file src/main/java/de/westnordost/streetcomplete/quests/opening_hours/OpeningHoursTagParser.kt) and it is implementation of https://github.com/westnordost/StreetComplete/issues/1651

**Comment by matkoniecz** [comment]
and now the hacky workaround is in https://github.com/westnordost/StreetComplete/pull/1676 - I would be happy to avoid it, but I have no good ideas how it can be done

**Comment by simonpoole** [comment]
I'm still weighing if this actually makes sense, what would work is making a copy of the original object, and then removing  the bits that are unsupported, but I agree that is likely somewhat error prone.

**Comment by matkoniecz** [comment]
I originally used this method and discovered in debugging that I missed some properties, that is why I switched to this variant. Especially as confirming whatever one actually tracked down all special cases is a tricky thing (`2012-2022 Feb+ Mo[1] -5 days 09:00-(sunset+00:50)` and its friends is saying hello)

And removing the bits that are unsupported would have greater potential to fail in case of adding new functionality covering yet another special OH syntax.

**Comment by simonpoole** [comment]
Thanks

**Pull request merged**
